// Spray GenX Studio v0.9 - data-driven categories, clean main menu
// Replace only GITHUB_TOKEN. Master file lives in GitHub; paste into Scriptable.
const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",PORTFOLIO_PATH="data/portfolio.json",CATEGORIES_PATH="data/categories.json",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE";
let CATS=[];const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;
function slug(v){return String(v||"project").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"project"}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function normImgs(p){return(p.images||[]).map(i=>typeof i==="string"?{path:i,visible:true,caption:""}:{path:i.path||"",visible:i.visible===false?false:true,caption:i.caption||""}).filter(i=>i.path)}
function normPortfolio(p){p.projects=p.projects||[];p.projects=p.projects.map((x,n)=>{let imgs=normImgs(x),cover=x.cover||(imgs[0]?imgs[0].path:"");return{id:x.id||`${slug(x.title||"project")}-${n+1}`,category:x.category||catId(),title:x.title||"Untitled Project",description:x.description||"",visible:x.visible===false?false:true,cover,images:imgs}});return p}
function normCats(c){let arr=(c.categories||[]).map((x,n)=>({id:x.id||slug(x.label||`category-${n+1}`),label:x.label||x.id||`Category ${n+1}`,headline:x.headline||x.label||x.id||`Category ${n+1}`,visible:x.visible===false?false:true,sort:Number.isFinite(x.sort)?x.sort:(n+1)*10}));arr.sort((a,b)=>(a.sort||0)-(b.sort||0));return{categories:arr}}
function catId(){let c=CATS.find(x=>x.visible!==false)||CATS[0];return c?c.id:"commercial-interiors"}
function catLabel(id){let f=CATS.find(c=>c.id===id);return f?f.label:id}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);if(!j.content||!j.sha)throw new Error(JSON.stringify(j,null,2));let txt=Data.fromBase64String(j.content.replace(/\n/g,"")).toRawString();return{json:JSON.parse(txt),sha:j.sha}}
async function put(path,b64,msg,sha=null){let body={message:msg,content:b64,branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function saveJson(path,obj,sha,msg){return await put(path,Data.fromString(JSON.stringify(obj,null,2)).toBase64String(),msg,sha)}
function stats(p){let s={};CATS.forEach(c=>s[c.id]={projects:0,photos:0});for(let pr of p.projects||[]){if(pr.visible===false||!s[pr.category])continue;s[pr.category].projects++;for(let im of pr.images||[])if(typeof im==="string"||im.visible!==false)s[pr.category].photos++}return s}
function statsMsg(p){let s=stats(p),tp=0,tf=0,lines=[];for(let c of CATS.filter(x=>x.visible!==false)){tp+=s[c.id].projects;tf+=s[c.id].photos;lines.push(`${c.label}: ${s[c.id].projects} projects / ${s[c.id].photos} photos`)}return[`Total: ${tp} projects / ${tf} photos`,"",...lines].join("\n")}
async function menu(){let a=new Alert();a.title="Spray GenX Studio";a.message="Portfolio manager";a.addAction("New Project");a.addAction("Manage Projects");a.addAction("Manage Categories");a.addAction("View Counts");a.addCancelAction("Cancel");return await a.presentAlert()}
async function pickCat(showHidden=false){let list=CATS.filter(c=>showHidden||c.visible!==false);let a=new Alert();a.title="Choose Category";list.forEach(c=>a.addAction(c.visible===false?`${c.label} [HIDDEN]`:c.label));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
function jpegExt(path){return/\.(jpe?g)$/i.test(String(path||""))}
async function pickFiles(){let out;try{out=await DocumentPicker.openFile(["public.jpeg","public.jpg"],true)}catch(e){out=await DocumentPicker.openFile()}let arr=Array.isArray(out)?out:[out],bad=arr.filter(p=>!jpegExt(p));if(bad.length)throw new Error("Only true .jpg/.jpeg files are allowed. Convert HEIC files to JPEG first.");return arr}
async function uploadFiles(paths,category,title,start=0){let fm=FileManager.local(),imgs=[],base=slug(title),time=stamp();for(let i=0;i<paths.length;i++){let n=String(start+i+1).padStart(3,"0"),repoPath=`images/portfolio/${category}/${base}-${time}-${n}.jpg`,data=fm.read(paths[i]);await put(repoPath,data.toBase64String(),`Upload portfolio image: ${title} ${n}`);imgs.push({path:repoPath,visible:true,caption:""})}return imgs}
async function newProject(file){let p=normPortfolio(file.json),cat=await pickCat(),title=await ask("Project Name","Commercial Open Deck Ceiling");if(!title)throw new Error("Project name required");let desc=await ask("Description","Sprayed exposed ceiling structure for a clean, uniform commercial finish."),files=await pickFiles();if(!files.length)throw new Error("No files selected");let imgs=await uploadFiles(files,cat.id,title,0),id=`${slug(title)}-${stamp()}`;p.projects.push({id,category:cat.id,title,description:desc,visible:true,cover:imgs[0].path,images:imgs});await saveJson(PORTFOLIO_PATH,p,file.sha,`Add portfolio project: ${title}`);let a=new Alert();a.title="Project Uploaded";a.message=`${title}\n\n${imgs.length} photo(s) uploaded to ${cat.label}.`;a.addAction("OK");await a.present()}
async function chooseProject(p){if(!p.projects.length){let a=new Alert();a.title="No Projects";a.message="There are no portfolio projects yet.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Project";p.projects.forEach(x=>a.addAction(`${x.title||"Untitled Project"}${x.visible===false?" [HIDDEN]":""}`));a.addCancelAction("Cancel");let i=await a.presentSheet();return i<0?null:{project:p.projects[i],index:i}}
async function manageProjects(file){let p=normPortfolio(file.json),sel=await chooseProject(p);if(!sel)return;let pr=sel.project,i=sel.index,a=new Alert();a.title=pr.title;a.message=`${catLabel(pr.category)}\n${pr.images.length} photo(s)`;a.addAction("Edit Title");a.addAction("Edit Description");a.addAction(pr.visible===false?"Show Project":"Hide Project");a.addAction("Change Category");a.addAction("Add Photos");a.addCancelAction("Cancel");let c=await a.presentSheet();if(c<0)return;if(c===0){let t=await ask("Edit Title","Project title",pr.title);if(t)p.projects[i].title=t}if(c===1)p.projects[i].description=await ask("Edit Description","Description",pr.description);if(c===2)p.projects[i].visible=pr.visible===false?true:false;if(c===3)p.projects[i].category=(await pickCat()).id;if(c===4){let files=await pickFiles(),imgs=await uploadFiles(files,p.projects[i].category,p.projects[i].title,p.projects[i].images.length);p.projects[i].images.push(...imgs);if(!p.projects[i].cover&&imgs[0])p.projects[i].cover=imgs[0].path}await saveJson(PORTFOLIO_PATH,p,file.sha,`Update portfolio project: ${p.projects[i].title}`);let d=new Alert();d.title="Project Updated";d.message=p.projects[i].title;d.addAction("OK");await d.present()}
async function manageCats(catFile){let data=normCats(catFile.json),a=new Alert();a.title="Manage Categories";a.message="Add, rename, hide/show, or edit headings. Hiding is safer than deleting.";a.addAction("Add Category");a.addAction("Edit Category");a.addAction("Hide/Show Category");a.addAction("Edit Headline");a.addCancelAction("Cancel");let c=await a.presentSheet();if(c<0)return;if(c===0){let label=await ask("New Category","Commercial Drywall");if(!label)return;let id=slug(label),sort=(data.categories.reduce((m,x)=>Math.max(m,x.sort||0),0)||0)+10;data.categories.push({id,label,headline:label,visible:true,sort})}else{let old=CATS;CATS=data.categories;let cat=await pickCat(true),idx=data.categories.findIndex(x=>x.id===cat.id);CATS=old;if(idx<0)return;if(c===1){let label=await ask("Rename Category","Category name",data.categories[idx].label);if(label)data.categories[idx].label=label}else if(c===2)data.categories[idx].visible=data.categories[idx].visible===false?true:false;else if(c===3)data.categories[idx].headline=await ask("Edit Headline","Section headline",data.categories[idx].headline||data.categories[idx].label)}await saveJson(CATEGORIES_PATH,data,catFile.sha,"Update portfolio categories");let d=new Alert();d.title="Categories Updated";d.message="Refresh website and Scriptable after category changes.";d.addAction("OK");await d.present()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let catFile=await getJson(CATEGORIES_PATH);CATS=normCats(catFile.json).categories;let file=await getJson(PORTFOLIO_PATH),p=normPortfolio(file.json),c=await menu();if(c===0)await newProject(file);else if(c===1)await manageProjects(file);else if(c===2)await manageCats(catFile);else if(c===3){let a=new Alert();a.title="Portfolio Counts";a.message=statsMsg(p);a.addAction("OK");await a.present()}}catch(e){let a=new Alert();a.title="Error";a.message=String(e);a.addAction("OK");await a.present()}
