// Spray GenX Converted Block Builder v1.0
// Separate Scriptable script for publishing converted inbox images.
// Replace only GITHUB_TOKEN.
// Reads data/converted-images.json and creates public blocks in data/image-library.json.

const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE";
const CONVERTED_PATH="data/converted-images.json",LIBRARY_PATH="data/image-library.json";
const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;

let LIBCATS=[];
function today(){return new Date().toISOString().slice(0,10)}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function slug(v){return String(v||"image-block").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"image-block"}
function splitTags(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function folderOf(p){let parts=String(p||"").split("/");return parts.length>2?parts.slice(2,-1).join("/")||"converted":"converted"}
function fileName(p){return String(p||"").split("/").pop()||p}
function unique(arr){return [...new Set(arr.filter(Boolean))]}
function normLib(l){let cats=(l.categories||[]).map((x,n)=>({id:x.id||slug(x.label||`category-${n+1}`),label:x.label||x.id||`Category ${n+1}`,sort:Number.isFinite(x.sort)?x.sort:(n+1)*10})).sort((a,b)=>(a.sort||0)-(b.sort||0));let blocks=(l.blocks||[]).map((b,n)=>({id:b.id||`${slug(b.title||"image-block")}-${n+1}`,title:b.title||"Untitled Image Block",category:b.category||(cats[0]?cats[0].id:"uncategorized"),date:b.date||today(),summary:b.summary||b.description||"",tags:Array.isArray(b.tags)?b.tags:splitTags(b.tags),visible:b.visible===false?false:true,images:(b.images||[]).map(i=>typeof i==="string"?{path:i,caption:"",visible:true}:{path:i.path||"",caption:i.caption||"",visible:i.visible===false?false:true}).filter(i=>i.path)}));return{version:l.version||1,updated:today(),notes:l.notes||"Bulk image library for Spray GenX job photos.",categories:cats,blocks}}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);if(!j.content||!j.sha)throw new Error(JSON.stringify(j,null,2));let txt=Data.fromBase64String(j.content.replace(/\n/g,"")).toRawString();return{json:JSON.parse(txt),sha:j.sha}}
async function putJson(path,obj,sha,msg){obj.updated=today();return await gh(api(path),"PUT",{message:msg,content:Data.fromString(JSON.stringify(obj,null,2)).toBase64String(),sha,branch:BRANCH})}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
async function askMulti(title,msg,fields){let a=new Alert();a.title=title;if(msg)a.message=msg;fields.forEach(f=>a.addTextField(f.placeholder||"",f.value||""));a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return fields.map((f,i)=>a.textFieldValue(i).trim())}
async function pickCat(){let list=LIBCATS.length?LIBCATS:[{id:"uncategorized",label:"Uncategorized"}];let a=new Alert();a.title="Public Category";list.forEach(c=>a.addAction(c.label));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
function getConvertedImages(converted){return (converted.images||[]).filter(x=>x.converted&&x.status!=="ignored")}
function usedPaths(lib){let set=new Set();(lib.blocks||[]).forEach(b=>(b.images||[]).forEach(im=>{let p=typeof im==="string"?im:im.path;if(p)set.add(p)}));return set}
async function chooseBatch(images){let groups={};images.forEach(x=>{let f=folderOf(x.converted);(groups[f]=groups[f]||[]).push(x)});let keys=Object.keys(groups).sort().reverse();if(!keys.length){let a=new Alert();a.title="No Converted Images";a.message="Upload raw images first, then wait for GitHub conversion.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Converted Batch";keys.forEach(k=>a.addAction(`${k} — ${groups[k].length} image(s)`));a.addAction("All Unpublished Converted Images");a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)return null;if(i===keys.length)return images;return groups[keys[i]]}
async function publishBlock(){let convFile=await getJson(CONVERTED_PATH),libFile=await getJson(LIBRARY_PATH),lib=normLib(libFile.json);LIBCATS=lib.categories;let used=usedPaths(lib);let available=getConvertedImages(convFile.json).filter(x=>!used.has(x.converted));let batch=await chooseBatch(available);if(!batch||!batch.length)return;let cat=await pickCat();let defaultTitle=folderOf(batch[0].converted).replace(/-/g," ").replace(/\b\w/g,c=>c.toUpperCase());let vals=await askMulti("Create Public Image Block",`${batch.length} converted image(s) will be added to photo-library.html.`,[{placeholder:"Block title",value:defaultTitle||"Converted Image Block"},{placeholder:"Summary",value:"Completed Spray GenX painting project."},{placeholder:"Tags comma separated",value:"painting, refinishing, completed work"},{placeholder:"Optional caption base",value:""}]);let title=vals[0];if(!title)throw new Error("Block title required");let captionBase=vals[3];let block={id:`${slug(title)}-${stamp()}`,title,category:cat.id,date:today(),summary:vals[1],tags:splitTags(vals[2]),visible:true,images:batch.map((x,i)=>({path:x.converted,caption:captionBase?`${captionBase} ${String(i+1).padStart(3,"0")}`:"",visible:true}))};lib.blocks.push(block);await putJson(LIBRARY_PATH,lib,libFile.sha,`Publish converted image block: ${title}`);let a=new Alert();a.title="Public Block Created";a.message=`${title}\n\n${block.images.length} image(s) added to ${cat.label}.\n\nBlock ID:\n${block.id}`;a.addAction("OK");await a.present()}
async function counts(){let convFile=await getJson(CONVERTED_PATH),libFile=await getJson(LIBRARY_PATH),lib=normLib(libFile.json);let used=usedPaths(lib),all=getConvertedImages(convFile.json),available=all.filter(x=>!used.has(x.converted));let groups=unique(available.map(x=>folderOf(x.converted))).map(f=>`${f}: ${available.filter(x=>folderOf(x.converted)===f).length}`).join("\n");let a=new Alert();a.title="Converted Images";a.message=`Converted total: ${all.length}\nUnpublished: ${available.length}\n\n${groups||"No unpublished converted images."}`;a.addAction("OK");await a.present()}
async function menu(){let a=new Alert();a.title="Converted Block Builder";a.message="Turn converted inbox images into public image-library blocks.";a.addAction("Create Public Block");a.addAction("View Unpublished Counts");a.addCancelAction("Cancel");return await a.presentAlert()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let c=await menu();if(c===0)await publishBlock();else if(c===1)await counts()}catch(e){let a=new Alert();a.title="Error";a.message=String(e);a.addAction("OK");await a.present()}
