// Spray GenX Unified v0.1 - one Scriptable entry point
// Replace only GITHUB_TOKEN. Paste this whole file into Scriptable.
const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE";
const PORTFOLIO_PATH="data/portfolio.json",CATEGORIES_PATH="data/categories.json",SETTINGS_PATH="data/site-settings.json";
const MANAGER_INDEX="data/manager/manager-index.json",DOC_INDEX="data/manager/document_index.json";
const ACTIVE_PROPOSALS=["draft","needs_revision","sent","pending","revision","waiting","follow_up"];
const INACTIVE_PROPOSALS=["converted_to_invoice","converted","approved","accepted","declined","expired","archived","void"];
const ACTIVE_INVOICES=["draft","sent","partial","unpaid","overdue"];
const INACTIVE_INVOICES=["paid","void","archived"];
let CATS=[];
const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;
function today(){return new Date().toISOString().slice(0,10)}
function now(){return new Date().toISOString()}
function year(){return new Date().getFullYear()}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function slug(v){return String(v||"project").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"project"}
function cleanMoney(v){return Number(String(v||"0").replace(/[^0-9.-]+/g,""))||0}
function money(v){return `$${cleanMoney(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function pad(n,w=4){return String(n).padStart(w,"0")}
function b64(s){return Data.fromString(s).toBase64String()}
function fromB64(s){return Data.fromBase64String(String(s||"").replace(/\n/g,"")).toRawString()}
function jsonText(o){return JSON.stringify(o,null,2)}
function imgPath(i){return typeof i==="string"?i:(i&&i.path?i.path:"")}
function shortPath(p){return String(p||"").split("/").pop()||p}
function ymdParts(d=today()){let x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,"0");return{year:y,month:`${y}-${m}`,week:isoWeek(x)}}
function isoWeek(d){let x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);let ys=new Date(Date.UTC(x.getUTCFullYear(),0,1)),w=Math.ceil((((x-ys)/86400000)+1)/7);return`${x.getUTCFullYear()}-W${String(w).padStart(2,"0")}`}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);return{json:JSON.parse(fromB64(j.content)),sha:j.sha,path}}
async function getMaybeJson(path){try{return await getJson(path)}catch(e){return{json:null,sha:null,path,error:e}}}
async function getSha(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);return j.sha||null}
async function put(path,content,msg,sha=null){let body={message:msg,content,branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function putJson(path,obj,sha,msg){return await put(path,b64(jsonText(obj)),msg,sha)}
async function del(path,msg){let sha=await getSha(path);if(!sha)return;return await gh(api(path),"DELETE",{message:msg,sha,branch:BRANCH})}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
async function confirmRemove(title,msg){let a=new Alert();a.title=title;a.message=msg;a.addDestructiveAction("Remove");a.addCancelAction("Cancel");return await a.presentAlert()===0}
function normImgs(p){return(p.images||[]).map(i=>typeof i==="string"?{path:i,visible:true,caption:""}:{path:i.path||"",visible:i.visible===false?false:true,caption:i.caption||""}).filter(i=>i.path)}
function normPortfolio(p){p.projects=p.projects||[];p.projects=p.projects.map((x,n)=>{let imgs=normImgs(x),cover=x.cover||(imgs[0]?imgs[0].path:"");return{id:x.id||`${slug(x.title||"project")}-${n+1}`,category:x.category||catId(),title:x.title||"Untitled Project",description:x.description||"",visible:x.visible===false?false:true,cover,images:imgs}});return p}
function normCats(c){let arr=(c.categories||[]).map((x,n)=>({id:x.id||slug(x.label||`category-${n+1}`),label:x.label||x.id||`Category ${n+1}`,headline:x.headline||x.label||x.id||`Category ${n+1}`,visible:x.visible===false?false:true,sort:Number.isFinite(x.sort)?x.sort:(n+1)*10}));arr.sort((a,b)=>(a.sort||0)-(b.sort||0));return{categories:arr}}
function catId(){let c=CATS.find(x=>x.visible!==false)||CATS[0];return c?c.id:"commercial-interiors"}
function catLabel(id){let f=CATS.find(c=>c.id===id);return f?f.label:id}
async function loadCats(){let catFile=await getJson(CATEGORIES_PATH);CATS=normCats(catFile.json).categories;return catFile}
async function savePortfolioLatest(obj,msg){let latest=await getJson(PORTFOLIO_PATH);return await putJson(PORTFOLIO_PATH,obj,latest.sha,msg)}
async function pickCat(showHidden=false){let list=CATS.filter(c=>showHidden||c.visible!==false);let a=new Alert();a.title="Choose Category";list.forEach(c=>a.addAction(c.visible===false?`${c.label} [HIDDEN]`:c.label));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
function jpegExt(path){return/\.(jpe?g)$/i.test(String(path||""))}
function logoExt(path){let p=String(path||"").toLowerCase();if(p.endsWith(".png"))return"png";if(p.endsWith(".jpg")||p.endsWith(".jpeg"))return"jpg";return""}
async function pickFileItems(){let out;try{out=await DocumentPicker.openFile(["public.jpeg","public.jpg"],true)}catch(e){out=await DocumentPicker.openFile()}let arr=Array.isArray(out)?out:[out],bad=arr.filter(p=>!jpegExt(p));if(bad.length)throw new Error("Only true .jpg/.jpeg files are allowed. Convert HEIC files to JPEG first.");let fm=FileManager.local();return arr.map(p=>({data:fm.read(p)}))}
async function uploadItems(items,category,title,start=0){let imgs=[],base=slug(title),time=stamp();for(let i=0;i<items.length;i++){let n=String(start+i+1).padStart(3,"0"),repoPath=`images/portfolio/${category}/${base}-${time}-${n}.jpg`;await put(repoPath,items[i].data.toBase64String(),`Upload portfolio image: ${title} ${n}`);imgs.push({path:repoPath,visible:true,caption:""})}return imgs}
async function replaceLogo(){let picked=await DocumentPicker.openFile(["public.png","public.jpeg","public.jpg"]),path=Array.isArray(picked)?picked[0]:picked,ext=logoExt(path);if(!ext)throw new Error("Choose a PNG or JPEG logo file.");let fm=FileManager.local(),repoPath=`images/logo-current.${ext}`;await put(repoPath,fm.read(path).toBase64String(),"Upload website logo",await getSha(repoPath));let settings=await getMaybeJson(SETTINGS_PATH);settings.json=settings.json||{};settings.json.logo=repoPath;await putJson(SETTINGS_PATH,settings.json,settings.sha,"Update website logo setting");await ok("Logo Updated",`Website logo now points to:\n${repoPath}`)}
async function newProject(file){let p=normPortfolio(file.json),cat=await pickCat(),title=await ask("Project Name","Commercial Open Deck Ceiling");if(!title)throw new Error("Project name required");let desc=await ask("Description","Sprayed exposed ceiling structure for a clean, uniform commercial finish."),items=await pickFileItems();if(!items.length)throw new Error("No files selected");let imgs=await uploadItems(items,cat.id,title,0),id=`${slug(title)}-${stamp()}`;p.projects.push({id,category:cat.id,title,description:desc,visible:true,cover:imgs[0].path,images:imgs});await savePortfolioLatest(p,`Add portfolio project: ${title}`);await ok("Project Uploaded",`${title}\n\n${imgs.length} photo(s) uploaded to ${cat.label}.`)}
async function chooseProject(p){if(!p.projects.length){await ok("No Projects","There are no portfolio projects yet.");return null}let a=new Alert();a.title="Choose Project";p.projects.forEach(x=>a.addAction(`${x.title||"Untitled Project"}${x.visible===false?" [HIDDEN]":""}`));a.addCancelAction("Cancel");let i=await a.presentSheet();return i<0?null:{project:p.projects[i],index:i}}
async function projectMenu(p,i){let pr=p.projects[i],a=new Alert();a.title=pr.title;a.message=`${catLabel(pr.category)}\n${pr.images.length} photo(s)`;a.addAction("Edit Title");a.addAction("Edit Description");a.addAction(pr.visible===false?"Show Project":"Hide Project");a.addAction("Change Category");a.addAction("Add Photos");a.addAction("Remove Photos");a.addAction("Done");return await a.presentSheet()}
async function removePhoto(p,i){let imgs=p.projects[i].images||[];if(!imgs.length){await ok("No Photos","This project has no photos to remove.");return false}let a=new Alert();a.title="Remove Photo";a.message="Select one photo to remove.";imgs.forEach((im,n)=>a.addAction(`${String(n+1).padStart(3,"0")} - ${shortPath(imgPath(im))}`));a.addCancelAction("Cancel");let x=await a.presentSheet();if(x<0)return false;let path=imgPath(imgs[x]);if(!await confirmRemove("Remove Photo?",shortPath(path)))return false;await del(path,`Remove portfolio image: ${shortPath(path)}`);imgs.splice(x,1);p.projects[i].images=imgs;p.projects[i].cover=imgs.length?imgPath(imgs[0]):"";return true}
async function manageProjects(file){let p=normPortfolio(file.json),sel=await chooseProject(p);if(!sel)return;let i=sel.index,changed=false;while(true){let c=await projectMenu(p,i);if(c<0||c===6)break;if(c===0){let t=await ask("Edit Title","Project title",p.projects[i].title);if(t){p.projects[i].title=t;changed=true}}else if(c===1){p.projects[i].description=await ask("Edit Description","Description",p.projects[i].description);changed=true}else if(c===2){p.projects[i].visible=p.projects[i].visible===false?true:false;changed=true}else if(c===3){p.projects[i].category=(await pickCat()).id;changed=true}else if(c===4){let items=await pickFileItems(),imgs=await uploadItems(items,p.projects[i].category,p.projects[i].title,p.projects[i].images.length);p.projects[i].images.push(...imgs);if(!p.projects[i].cover&&imgs[0])p.projects[i].cover=imgs[0].path;changed=true}else if(c===5){changed=await removePhoto(p,i)}if(changed){await savePortfolioLatest(p,`Update portfolio project: ${p.projects[i].title}`);await ok("Saved","Choose another edit or tap Done.");changed=false}}}
async function manageCats(catFile){let data=normCats(catFile.json),a=new Alert();a.title="Manage Categories";a.message="Add, rename, hide/show, or edit headings. Hiding is safer than deleting.";a.addAction("Add Category");a.addAction("Edit Category");a.addAction("Hide/Show Category");a.addAction("Edit Headline");a.addCancelAction("Cancel");let c=await a.presentSheet();if(c<0)return;if(c===0){let label=await ask("New Category","Commercial Drywall");if(!label)return;let id=slug(label),sort=(data.categories.reduce((m,x)=>Math.max(m,x.sort||0),0)||0)+10;data.categories.push({id,label,headline:label,visible:true,sort})}else{let old=CATS;CATS=data.categories;let cat=await pickCat(true),idx=data.categories.findIndex(x=>x.id===cat.id);CATS=old;if(idx<0)return;if(c===1){let label=await ask("Rename Category","Category name",data.categories[idx].label);if(label)data.categories[idx].label=label}else if(c===2)data.categories[idx].visible=data.categories[idx].visible===false?true:false;else if(c===3)data.categories[idx].headline=await ask("Edit Headline","Section headline",data.categories[idx].headline||data.categories[idx].label)}await putJson(CATEGORIES_PATH,data,catFile.sha,"Update portfolio categories");await ok("Categories Updated","Refresh website and Scriptable after category changes.")}
function portfolioStats(p){let s={};CATS.forEach(c=>s[c.id]={projects:0,photos:0});for(let pr of p.projects||[]){if(pr.visible===false||!s[pr.category])continue;s[pr.category].projects++;for(let im of pr.images||[])if(typeof im==="string"||im.visible!==false)s[pr.category].photos++}return s}
function portfolioStatsMsg(p){let s=portfolioStats(p),tp=0,tf=0,lines=[];for(let c of CATS.filter(x=>x.visible!==false)){tp+=s[c.id].projects;tf+=s[c.id].photos;lines.push(`${c.label}: ${s[c.id].projects} projects / ${s[c.id].photos} photos`)}return[`Total: ${tp} projects / ${tf} photos`,"",...lines].join("\n")}
async function backupFile(path,label){let f=await getMaybeJson(path);if(!f.json)return null;let d=today().slice(0,7).replace("-","/"),name=path.split("/").pop();let backup=`data/manager/backups/${d}/records/${label}/${stamp()}-${name}`;await putJson(backup,f.json,null,`Backup ${label}: ${name}`);return backup}
async function safeSaveJson(path,obj,label,msg){let parsed=JSON.parse(jsonText(obj)),current=await getMaybeJson(path);if(current.json)await backupFile(path,label);await putJson(path,parsed,current.sha,msg);return path}
async function loadCore(){return{manager:await getJson(MANAGER_INDEX),docs:await getJson(DOC_INDEX)}}
function allDocs(docIndex,type){return(docIndex.documents||[]).filter(d=>d.type===type)}
function nextManagerId(docIndex,type){let prefix=type==="proposal"?"PROP":"INV",rx=new RegExp(`^${prefix}-${year()}-(\\d+)$`),max=0;for(let d of allDocs(docIndex,type)){let m=String(d.id||"").match(rx);if(m)max=Math.max(max,Number(m[1]))}return`${prefix}-${year()}-${pad(max+1)}`}
function nextDocNo(docIndex,type){let prefix=type==="proposal"?"SGX":"INV",rx=new RegExp(`^${prefix}-${year()}-(\\d+)$`),max=0;for(let d of allDocs(docIndex,type)){let m=String(d.number||"").match(rx);if(m)max=Math.max(max,Number(m[1]))}return`${prefix}-${year()}-${pad(max+1,3)}`}
function documentPath(type,id){return`data/manager/${type==="proposal"?"proposals":"invoices"}/${id}.json`}
function isActive(type,status,paymentStatus=""){let s=String(status||"draft").toLowerCase(),p=String(paymentStatus||"").toLowerCase();if(type==="proposal")return ACTIVE_PROPOSALS.includes(s)&&!INACTIVE_PROPOSALS.includes(s);return (ACTIVE_INVOICES.includes(s)||ACTIVE_INVOICES.includes(p))&&!INACTIVE_INVOICES.includes(s)&&!INACTIVE_INVOICES.includes(p)}
function indexEntry(record,type,path){let parts=ymdParts(record.date||today()),amount=cleanMoney(record.price),status=record.manager?.status||"draft",pay=record.manager?.payment_status||"",active=isActive(type,status,pay);return{id:type==="proposal"?record.manager.proposal_id:record.manager.invoice_id,type,number:record.docNo,status,payment_status:pay||undefined,active,history:!active,customer_id:record.manager?.customer_id||"",customer_name:record.client||"",job_id:record.manager?.job_id||"",job_name:record.project||"",city:record.location?.city||"",state:record.location?.state||"OH",amount,balance_due:type==="invoice"?cleanMoney(record.manager?.balance_due||record.price):undefined,created_date:record.audit?.created_at?String(record.audit.created_at).slice(0,10):(record.date||today()),updated_date:today(),due_date:record.manager?.due_date||"",year:parts.year,month:parts.month,week:parts.week,source_json:path,source_html:record.manager?.html_file||"",source_pdf:record.manager?.pdf_file||"",tags:[type,active?"active":"history",String(status||"").toLowerCase()].filter(Boolean),search_text:[record.docNo,record.client,record.project,record.location?.city,record.location?.state,type,status,pay].filter(Boolean).join(" ")}}
function upsertIndex(docIndex,entry){docIndex.documents=docIndex.documents||[];docIndex.documents=docIndex.documents.filter(d=>d.id!==entry.id);docIndex.documents.push(entry);docIndex.updated=today();return docIndex}
function upsertManagerIndex(manager,type,path){manager.records=manager.records||{};let key=type==="proposal"?"proposals":"invoices";manager.records[key]=manager.records[key]||[];if(!manager.records[key].includes(path))manager.records[key].push(path);manager.updated=today();return manager}
async function saveManagerDocument(record,type){let core=await loadCore(),docs=core.docs.json,manager=core.manager.json,id=type==="proposal"?record.manager.proposal_id:record.manager.invoice_id,path=documentPath(type,id);record.manager.json_path=path;record.audit=record.audit||{};record.audit.updated_at=now();record.audit.version=Number(record.audit.version||0)+1;record.audit.last_backup_at=now();await safeSaveJson(path,record,type,`Save ${type}: ${record.docNo}`);upsertIndex(docs,indexEntry(record,type,path));upsertManagerIndex(manager,type,path);await backupFile(DOC_INDEX,"indexes");await putJson(DOC_INDEX,docs,core.docs.sha,`Update document index: ${record.docNo}`);let freshManager=await getJson(MANAGER_INDEX);await backupFile(MANAGER_INDEX,"indexes");await putJson(MANAGER_INDEX,manager,freshManager.sha,`Update manager index: ${record.docNo}`);return{record,path}}
async function pickStatus(type){let list=type==="proposal"?[...ACTIVE_PROPOSALS,...INACTIVE_PROPOSALS]:[...ACTIVE_INVOICES,...INACTIVE_INVOICES];let a=new Alert();a.title="Status";list.forEach(x=>a.addAction(x));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
async function newDocument(type){let core=await loadCore(),docs=core.docs.json,id=nextManagerId(docs,type),docNo=nextDocNo(docs,type),date=today();let client=await ask(type==="proposal"?"Proposal Customer":"Invoice Customer","Customer / contractor"),project=await ask("Job / Project","Canton Car Wash Brick Coating"),price=money(await ask("Amount","15750")),scope=await ask("Scope","Brief scope summary"),notes=await ask("Notes","Terms / notes",""),status=await pickStatus(type);let rec={docType:type,docNo,date,client,project,price,scope,notes,location:{city:"",state:"OH"},manager:type==="proposal"?{proposal_id:id,job_id:"",customer_id:"",status,revision_number:0,converted_to_invoice_id:"",html_file:"",pdf_file:"",json_path:""}:{invoice_id:id,job_id:"",customer_id:"",proposal_id:"",status,payment_status:status==="paid"?"paid":"unpaid",amount_paid:"$0.00",balance_due:price,html_file:"",pdf_file:"",json_path:""},audit:{created_by:"owner",created_at:now(),updated_at:now(),archived:false,archive_reason:"",version:1,last_backup_at:"",checksum:"future-checksum"}};let saved=await saveManagerDocument(rec,type);await ok("Saved",`${docNo}\n${saved.path}\n\nDocument index and manager index updated.`)}
async function convertProposal(){let core=await loadCore(),proposals=allDocs(core.docs.json,"proposal").filter(d=>d.active);if(!proposals.length)throw new Error("No active proposals found.");let a=new Alert();a.title="Convert Proposal";proposals.forEach(p=>a.addAction(`${p.number} - ${p.customer_name}`));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)return;let p=proposals[i],pf=await getJson(p.source_json),prop=pf.json,docs=core.docs.json,id=nextManagerId(docs,"invoice"),docNo=nextDocNo(docs,"invoice"),price=prop.price||money(p.amount);let inv={docType:"invoice",docNo,date:today(),client:prop.client||p.customer_name,project:prop.project||p.job_name,price,scope:prop.scope||"",notes:prop.notes||"",location:prop.location||{city:p.city||"",state:p.state||"OH"},manager:{invoice_id:id,job_id:prop.manager?.job_id||p.job_id||"",customer_id:prop.manager?.customer_id||p.customer_id||"",proposal_id:prop.manager?.proposal_id||p.id,status:"draft",payment_status:"unpaid",amount_paid:"$0.00",balance_due:price,html_file:"",pdf_file:"",json_path:""},audit:{created_by:"owner",created_at:now(),updated_at:now(),archived:false,archive_reason:"",version:1,last_backup_at:"",checksum:"future-checksum"}};prop.manager=prop.manager||{};prop.manager.status="converted_to_invoice";prop.manager.converted_to_invoice_id=id;prop.audit=prop.audit||{};prop.audit.updated_at=now();prop.audit.version=Number(prop.audit.version||0)+1;await saveManagerDocument(prop,"proposal");let saved=await saveManagerDocument(inv,"invoice");await ok("Converted",`${p.number} -> ${docNo}\n${saved.path}`)}
async function documentCounts(){let d=(await getJson(DOC_INDEX)).json,ap=allDocs(d,"proposal").filter(x=>x.active).length,hp=allDocs(d,"proposal").filter(x=>x.history).length,ai=allDocs(d,"invoice").filter(x=>x.active).length,hi=allDocs(d,"invoice").filter(x=>x.history).length;await ok("Document Counts",`Active proposals: ${ap}\nHistory proposals: ${hp}\nOpen invoices: ${ai}\nHistory invoices: ${hi}`)}
async function ok(title,msg){let a=new Alert();a.title=title;a.message=msg;a.addAction("OK");await a.present()}
async function mainMenu(){let a=new Alert();a.title="Spray GenX";a.message="Unified field app";a.addAction("New Proposal");a.addAction("New Invoice");a.addAction("Convert Proposal to Invoice");a.addAction("Document Counts");a.addAction("New Portfolio Project");a.addAction("Manage Portfolio Projects");a.addAction("Manage Categories");a.addAction("Portfolio Counts");a.addAction("Replace Website Logo");a.addCancelAction("Cancel");return await a.presentSheet()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let catFile=await loadCats(),portfolio=await getJson(PORTFOLIO_PATH),choice=await mainMenu();if(choice===0)await newDocument("proposal");else if(choice===1)await newDocument("invoice");else if(choice===2)await convertProposal();else if(choice===3)await documentCounts();else if(choice===4)await newProject(portfolio);else if(choice===5)await manageProjects(portfolio);else if(choice===6)await manageCats(catFile);else if(choice===7)await ok("Portfolio Counts",portfolioStatsMsg(normPortfolio(portfolio.json)));else if(choice===8)await replaceLogo()}catch(e){await ok("Error",String(e))}
