// Spray GenX Manager v0.1 - Scriptable proposal/invoice sync MVP
// Replace only GITHUB_TOKEN. Paste this whole file into Scriptable.
const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE";
const MANAGER_INDEX="data/manager/manager-index.json",DOC_INDEX="data/manager/document_index.json";
const ACTIVE_PROPOSALS=["draft","needs_revision","sent","pending","revision","waiting","follow_up"];
const INACTIVE_PROPOSALS=["converted_to_invoice","converted","approved","accepted","declined","expired","archived","void"];
const ACTIVE_INVOICES=["draft","sent","partial","unpaid","overdue"];
const INACTIVE_INVOICES=["paid","void","archived"];
const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;
function today(){return new Date().toISOString().slice(0,10)}
function now(){return new Date().toISOString()}
function year(){return new Date().getFullYear()}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function cleanMoney(v){return Number(String(v||"0").replace(/[^0-9.-]+/g,""))||0}
function money(v){return `$${cleanMoney(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function pad(n,w=4){return String(n).padStart(w,"0")}
function b64(s){return Data.fromString(s).toBase64String()}
function fromB64(s){return Data.fromBase64String(String(s||"").replace(/\n/g,"")).toRawString()}
function jsonText(o){return JSON.stringify(o,null,2)}
function ymdParts(d=today()){let x=new Date(d),y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,"0");return{year:y,month:`${y}-${m}`,week:isoWeek(x)}}
function isoWeek(d){let x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);let ys=new Date(Date.UTC(x.getUTCFullYear(),0,1)),w=Math.ceil((((x-ys)/86400000)+1)/7);return`${x.getUTCFullYear()}-W${String(w).padStart(2,"0")}`}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);return{json:JSON.parse(fromB64(j.content)),sha:j.sha,path}}
async function getMaybeJson(path){try{return await getJson(path)}catch(e){return{json:null,sha:null,path,error:e}}}
async function putJson(path,obj,sha,msg){let body={message:msg,content:b64(jsonText(obj)),branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function putText(path,text,sha,msg){let body={message:msg,content:b64(text),branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function backupFile(path,label){let f=await getMaybeJson(path);if(!f.json)return null;let d=today().slice(0,7).replace("-","/"),name=path.split("/").pop();let backup=`data/manager/backups/${d}/records/${label}/${stamp()}-${name}`;await putJson(backup,f.json,null,`Backup ${label}: ${name}`);return backup}
async function safeSaveJson(path,obj,label,msg){let parsed=JSON.parse(jsonText(obj));let current=await getMaybeJson(path);if(current.json)await backupFile(path,label);await putJson(path,parsed,current.sha,msg);return path}
async function loadCore(){return{manager:await getJson(MANAGER_INDEX),docs:await getJson(DOC_INDEX)}}
function allDocs(docIndex,type){return(docIndex.documents||[]).filter(d=>d.type===type)}
function nextManagerId(docIndex,type){let prefix=type==="proposal"?"PROP":"INV",rx=new RegExp(`^${prefix}-${year()}-(\\d+)$`),max=0;for(let d of allDocs(docIndex,type)){let m=String(d.id||"").match(rx);if(m)max=Math.max(max,Number(m[1]))}return`${prefix}-${year()}-${pad(max+1)}`}
function nextDocNo(docIndex,type){let prefix=type==="proposal"?"SGX":"INV",rx=new RegExp(`^${prefix}-${year()}-(\\d+)$`),max=0;for(let d of allDocs(docIndex,type)){let m=String(d.number||"").match(rx);if(m)max=Math.max(max,Number(m[1]))}return`${prefix}-${year()}-${pad(max+1,3)}`}
function documentPath(type,id){return`data/manager/${type==="proposal"?"proposals":"invoices"}/${id}.json`}
function isActive(type,status,paymentStatus=""){let s=String(status||"draft").toLowerCase(),p=String(paymentStatus||"").toLowerCase();if(type==="proposal")return ACTIVE_PROPOSALS.includes(s)&&!INACTIVE_PROPOSALS.includes(s);return (ACTIVE_INVOICES.includes(s)||ACTIVE_INVOICES.includes(p))&&!INACTIVE_INVOICES.includes(s)&&!INACTIVE_INVOICES.includes(p)}
function searchText(d){return[d.number,d.customer_name,d.job_name,d.city,d.state,d.type,d.status,d.payment_status].filter(Boolean).join(" ")}
function indexEntry(record,type,path){let parts=ymdParts(record.date||today()),amount=cleanMoney(record.price),status=record.manager?.status||"draft",pay=record.manager?.payment_status||"";return{id:type==="proposal"?record.manager.proposal_id:record.manager.invoice_id,type,number:record.docNo,status,payment_status:pay||undefined,active:isActive(type,status,pay),history:!isActive(type,status,pay),customer_id:record.manager?.customer_id||"",customer_name:record.client||"",job_id:record.manager?.job_id||"",job_name:record.project||"",city:record.location?.city||"",state:record.location?.state||"OH",amount,balance_due:type==="invoice"?cleanMoney(record.manager?.balance_due||record.price):undefined,created_date:record.audit?.created_at?String(record.audit.created_at).slice(0,10):(record.date||today()),updated_date:today(),due_date:record.manager?.due_date||"",year:parts.year,month:parts.month,week:parts.week,source_json:path,source_html:record.manager?.html_file||"",source_pdf:record.manager?.pdf_file||"",tags:[type,isActive(type,status,pay)?"active":"history",String(status||"").toLowerCase()].filter(Boolean),search_text:searchText({number:record.docNo,customer_name:record.client,job_name:record.project,city:record.location?.city,state:record.location?.state,type,status,payment_status:pay})}}
function upsertIndex(docIndex,entry){docIndex.documents=docIndex.documents||[];docIndex.documents=docIndex.documents.filter(d=>d.id!==entry.id);docIndex.documents.push(entry);docIndex.updated=today();return docIndex}
function upsertManagerIndex(manager,type,path){manager.records=manager.records||{};let key=type==="proposal"?"proposals":"invoices";manager.records[key]=manager.records[key]||[];if(!manager.records[key].includes(path))manager.records[key].push(path);manager.updated=today();return manager}
async function saveManagerDocument(record,type){let core=await loadCore(),docs=core.docs.json,manager=core.manager.json,id=type==="proposal"?record.manager.proposal_id:record.manager.invoice_id,path=documentPath(type,id);record.manager.json_path=path;record.audit=record.audit||{};record.audit.updated_at=now();record.audit.version=Number(record.audit.version||0)+1;record.audit.last_backup_at=now();await safeSaveJson(path,record,type,`Save ${type}: ${record.docNo}`);let entry=indexEntry(record,type,path);upsertIndex(docs,entry);upsertManagerIndex(manager,type,path);await backupFile(DOC_INDEX,"indexes");await putJson(DOC_INDEX,docs,core.docs.sha,`Update document index: ${record.docNo}`);let freshManager=await getJson(MANAGER_INDEX);await backupFile(MANAGER_INDEX,"indexes");await putJson(MANAGER_INDEX,manager,freshManager.sha,`Update manager index: ${record.docNo}`);return{record,path,entry}}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
async function pickStatus(type){let list=type==="proposal"?[...ACTIVE_PROPOSALS,...INACTIVE_PROPOSALS]:[...ACTIVE_INVOICES,...INACTIVE_INVOICES];let a=new Alert();a.title="Status";list.forEach(x=>a.addAction(x));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
async function newDocument(type){let core=await loadCore(),docs=core.docs.json,id=nextManagerId(docs,type),docNo=nextDocNo(docs,type),date=today();let client=await ask(type==="proposal"?"Proposal Customer":"Invoice Customer","Customer / contractor"),project=await ask("Job / Project","Canton Car Wash Brick Coating"),price=money(await ask("Amount","15750")),scope=await ask("Scope","Brief scope summary"),notes=await ask("Notes","Terms / notes",""),status=await pickStatus(type);let rec={docType:type,docNo,date,client,project,price,scope,notes,location:{city:"",state:"OH"},manager:type==="proposal"?{proposal_id:id,job_id:"",customer_id:"",status,revision_number:0,converted_to_invoice_id:"",html_file:"",pdf_file:"",json_path:""}:{invoice_id:id,job_id:"",customer_id:"",proposal_id:"",status,payment_status:status==="paid"?"paid":"unpaid",amount_paid:"$0.00",balance_due:price,html_file:"",pdf_file:"",json_path:""},audit:{created_by:"owner",created_at:now(),updated_at:now(),archived:false,archive_reason:"",version:1,last_backup_at:"",checksum:"future-checksum"}};let saved=await saveManagerDocument(rec,type);let a=new Alert();a.title="Saved";a.message=`${docNo}\n${saved.path}\n\nDocument index and manager index updated.`;a.addAction("OK");await a.present()}
async function convertProposal(){let core=await loadCore(),proposals=allDocs(core.docs.json,"proposal").filter(d=>d.active);if(!proposals.length)throw new Error("No active proposals found.");let a=new Alert();a.title="Convert Proposal";proposals.forEach(p=>a.addAction(`${p.number} - ${p.customer_name}`));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)return;let p=proposals[i],pf=await getJson(p.source_json),prop=pf.json,docs=core.docs.json,id=nextManagerId(docs,"invoice"),docNo=nextDocNo(docs,"invoice"),price=prop.price||money(p.amount);let inv={docType:"invoice",docNo,date:today(),client:prop.client||p.customer_name,project:prop.project||p.job_name,price,scope:prop.scope||"",notes:prop.notes||"",location:prop.location||{city:p.city||"",state:p.state||"OH"},manager:{invoice_id:id,job_id:prop.manager?.job_id||p.job_id||"",customer_id:prop.manager?.customer_id||p.customer_id||"",proposal_id:prop.manager?.proposal_id||p.id,status:"draft",payment_status:"unpaid",amount_paid:"$0.00",balance_due:price,html_file:"",pdf_file:"",json_path:""},audit:{created_by:"owner",created_at:now(),updated_at:now(),archived:false,archive_reason:"",version:1,last_backup_at:"",checksum:"future-checksum"}};prop.manager=prop.manager||{};prop.manager.status="converted_to_invoice";prop.manager.converted_to_invoice_id=id;prop.audit=prop.audit||{};prop.audit.updated_at=now();prop.audit.version=Number(prop.audit.version||0)+1;await saveManagerDocument(prop,"proposal");let saved=await saveManagerDocument(inv,"invoice");let done=new Alert();done.title="Converted";done.message=`${p.number} -> ${docNo}\n${saved.path}`;done.addAction("OK");await done.present()}
async function viewCounts(){let d=(await getJson(DOC_INDEX)).json,ap=allDocs(d,"proposal").filter(x=>x.active).length,hp=allDocs(d,"proposal").filter(x=>x.history).length,ai=allDocs(d,"invoice").filter(x=>x.active).length,hi=allDocs(d,"invoice").filter(x=>x.history).length;let a=new Alert();a.title="Document Counts";a.message=`Active proposals: ${ap}\nHistory proposals: ${hp}\nOpen invoices: ${ai}\nHistory invoices: ${hi}`;a.addAction("OK");await a.present()}
async function menu(){let a=new Alert();a.title="Spray GenX Manager";a.message="Proposal / invoice Manager sync";a.addAction("New Proposal");a.addAction("New Invoice");a.addAction("Convert Proposal to Invoice");a.addAction("View Counts");a.addCancelAction("Cancel");return await a.presentSheet()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let c=await menu();if(c===0)await newDocument("proposal");else if(c===1)await newDocument("invoice");else if(c===2)await convertProposal();else if(c===3)await viewCounts()}catch(e){let a=new Alert();a.title="Error";a.message=String(e);a.addAction("OK");await a.present()}
