// Spray GenX Image Library v1.3 - public image library uploader + converted image publisher
// Replace only GITHUB_TOKEN. Master file lives in GitHub; paste into the Image Library Scriptable script.
const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",LIBRARY_PATH="data/image-library.json",CONVERTED_PATH="data/converted-images.json",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE",MAX_BATCH=20;
let LIBCATS=[];const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;
function slug(v){return String(v||"image-block").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"image-block"}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function today(){return new Date().toISOString().slice(0,10)}
function splitTags(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function imgPath(i){return typeof i==="string"?i:(i&&i.path?i.path:"")}
function folderOf(p){let parts=String(p||"").split("/");return parts.length>2?parts.slice(2,-1).join("/")||"converted":"converted"}
function unique(arr){return[...new Set(arr.filter(Boolean))]}
function titleCase(v){return String(v||"").replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase())}
function normLib(l){let cats=(l.categories||[]).map((x,n)=>({id:x.id||slug(x.label||`category-${n+1}`),label:x.label||x.id||`Category ${n+1}`,sort:Number.isFinite(x.sort)?x.sort:(n+1)*10})).sort((a,b)=>(a.sort||0)-(b.sort||0));let blocks=(l.blocks||[]).map((b,n)=>({id:b.id||`${slug(b.title||"image-block")}-${n+1}`,title:b.title||"Untitled Image Block",category:b.category||(cats[0]?cats[0].id:"uncategorized"),date:b.date||today(),summary:b.summary||b.description||"",tags:Array.isArray(b.tags)?b.tags:splitTags(b.tags),visible:b.visible===false?false:true,images:(b.images||[]).map(i=>typeof i==="string"?{path:i,caption:"",visible:true}:{path:i.path||"",caption:i.caption||"",visible:i.visible===false?false:true}).filter(i=>i.path)}));return{version:l.version||1,updated:today(),notes:l.notes||"Bulk image library for Spray GenX job photos.",categories:cats,blocks}}
function libCatLabel(id){let f=LIBCATS.find(c=>c.id===id);return f?f.label:id}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);if(!j.content||!j.sha)throw new Error(JSON.stringify(j,null,2));let txt=Data.fromBase64String(j.content.replace(/\n/g,"")).toRawString();return{json:JSON.parse(txt),sha:j.sha}}
async function getSha(path){try{let j=await gh(`${api(path)}?ref=${BRANCH}`);return j.sha||null}catch(e){return null}}
async function put(path,b64,msg,sha=null){let body={message:msg,content:b64,branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function del(path,msg){let sha=await getSha(path);if(!sha)return;return await gh(api(path),"DELETE",{message:msg,sha,branch:BRANCH})}
async function saveJson(path,obj,sha,msg){obj.updated=today();return await put(path,Data.fromString(JSON.stringify(obj,null,2)).toBase64String(),msg,sha)}
async function saveLibraryLatest(obj,msg){let latest=await getJson(LIBRARY_PATH);return await saveJson(LIBRARY_PATH,normLib(obj),latest.sha,msg)}
function fileExt(path){let p=String(path||"").toLowerCase();if(p.endsWith(".jpg")||p.endsWith(".jpeg"))return"jpg";if(p.endsWith(".png"))return"png";return""}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
async function askMulti(title,msg,fields){let a=new Alert();a.title=title;if(msg)a.message=msg;fields.forEach(f=>a.addTextField(f.placeholder||"",f.value||""));a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return fields.map((f,i)=>a.textFieldValue(i).trim())}
async function yesNo(title,msg,yes="Add More",no="Done"){let a=new Alert();a.title=title;a.message=msg;a.addAction(yes);a.addCancelAction(no);return await a.presentAlert()===0}
async function pickerOnce(){let out;try{out=await DocumentPicker.openFile(["public.jpeg","public.jpg","public.png"],true)}catch(e){out=await DocumentPicker.openFile()}return Array.isArray(out)?out:[out]}
async function pickFileItems(){let paths=[],seen=new Set();while(paths.length<MAX_BATCH){let picked=await pickerOnce();for(let p of picked){if(!p||seen.has(p))continue;seen.add(p);paths.push(p);if(paths.length>=MAX_BATCH)break}if(paths.length>=MAX_BATCH)break;if(picked.length>1)break;let more=await yesNo("Add More Images?",`${paths.length} image(s) selected. Add more to this same image block?\n\nLimit: ${MAX_BATCH}`,"Add More","Done");if(!more)break}let bad=paths.filter(p=>!fileExt(p));if(bad.length)throw new Error("Only .jpg, .jpeg, or .png files are allowed here. Use the Inbox Uploader for HEIC/HEIF/mixed file conversion first.");let fm=FileManager.local();return paths.slice(0,MAX_BATCH).map(p=>({path:p,ext:fileExt(p),data:fm.read(p)}))}
async function pickLibCat(){let list=LIBCATS.length?LIBCATS:[{id:"uncategorized",label:"Uncategorized"}];let a=new Alert();a.title="Choose Image Category";list.forEach(c=>a.addAction(c.label));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
async function uploadLibraryItems(items,block,start=0){let imgs=[],base=slug(block.title),time=stamp(),cat=block.category||"uncategorized";for(let i=0;i<items.length;i++){let n=String(start+i+1).padStart(3,"0"),ext=items[i].ext||"jpg",repoPath=`images/library/${cat}/${base}-${time}-${n}.${ext}`;await put(repoPath,items[i].data.toBase64String(),`Upload library image: ${block.title} ${n}`);imgs.push({path:repoPath,visible:true,caption:block.captionBase?`${block.captionBase} ${n}`:""})}return imgs}
async function uploadBlock(libFile){let lib=normLib(libFile.json);LIBCATS=lib.categories;let cat=await pickLibCat();let vals=await askMulti("New Image Block","For JPG/PNG files already ready for the web. For HEIC/mixed files, use Inbox Uploader first, then Publish Converted Images here.",[{placeholder:"Block title",value:"Commercial Black Ceiling"},{placeholder:"Summary",value:"Completed Spray GenX painting project."},{placeholder:"Tags comma separated",value:"painting, refinishing, completed work"},{placeholder:"Optional caption base",value:""}]);let title=vals[0];if(!title)throw new Error("Block title required");let items=await pickFileItems();if(!items.length)throw new Error("No files selected");let block={id:`${slug(title)}-${stamp()}`,title,category:cat.id,date:today(),summary:vals[1],tags:splitTags(vals[2]),visible:true,captionBase:vals[3]};block.images=await uploadLibraryItems(items,block,0);delete block.captionBase;lib.blocks.push(block);await saveLibraryLatest(lib,`Add image library block: ${title}`);let a=new Alert();a.title="Image Block Uploaded";a.message=`${title}\n\n${block.images.length} image(s) uploaded to ${cat.label}.\n\nBlock ID:\n${block.id}`;a.addAction("OK");await a.present()}
function getConvertedImages(converted){return(converted.images||[]).filter(x=>x.converted&&x.status!=="ignored")}
function usedPaths(lib){let set=new Set();(lib.blocks||[]).forEach(b=>(b.images||[]).forEach(im=>{let p=imgPath(im);if(p)set.add(p)}));return set}
async function chooseConvertedBatch(images){let groups={};images.forEach(x=>{let f=folderOf(x.converted);(groups[f]=groups[f]||[]).push(x)});let keys=Object.keys(groups).sort().reverse();if(!keys.length){let a=new Alert();a.title="No Converted Images";a.message="Use the Inbox Uploader first, then wait for GitHub conversion.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Converted Batch";keys.forEach(k=>a.addAction(`${k} - ${groups[k].length} image(s)`));a.addAction("All Unpublished Converted Images");a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)return null;if(i===keys.length)return images;return groups[keys[i]]}
async function publishConvertedImages(){let libFile=await getJson(LIBRARY_PATH),convFile=await getJson(CONVERTED_PATH),lib=normLib(libFile.json);LIBCATS=lib.categories;let used=usedPaths(lib),available=getConvertedImages(convFile.json).filter(x=>!used.has(x.converted));let batch=await chooseConvertedBatch(available);if(!batch||!batch.length)return;let cat=await pickLibCat();let defaultTitle=titleCase(folderOf(batch[0].converted));let vals=await askMulti("Publish Converted Images",`${batch.length} converted image(s) will be added to the public image library.`,[{placeholder:"Block title",value:defaultTitle||"Converted Image Block"},{placeholder:"Summary",value:"Completed Spray GenX painting project."},{placeholder:"Tags comma separated",value:"painting, refinishing, completed work"},{placeholder:"Optional caption base",value:""}]);let title=vals[0];if(!title)throw new Error("Block title required");let captionBase=vals[3];let block={id:`${slug(title)}-${stamp()}`,title,category:cat.id,date:today(),summary:vals[1],tags:splitTags(vals[2]),visible:true,images:batch.map((x,i)=>({path:x.converted,caption:captionBase?`${captionBase} ${String(i+1).padStart(3,"0")}`:"",visible:true}))};lib.blocks.push(block);await saveLibraryLatest(lib,`Publish converted image block: ${title}`);let a=new Alert();a.title="Converted Block Published";a.message=`${title}\n\n${block.images.length} converted image(s) added to ${cat.label}.\n\nBlock ID:\n${block.id}`;a.addAction("OK");await a.present()}
async function convertedCounts(){let libFile=await getJson(LIBRARY_PATH),convFile=await getJson(CONVERTED_PATH),lib=normLib(libFile.json),used=usedPaths(lib),all=getConvertedImages(convFile.json),available=all.filter(x=>!used.has(x.converted));let groups=unique(available.map(x=>folderOf(x.converted))).map(f=>`${f}: ${available.filter(x=>folderOf(x.converted)===f).length}`).join("\n");let a=new Alert();a.title="Converted Images";a.message=`Converted total: ${all.length}\nUnpublished: ${available.length}\n\n${groups||"No unpublished converted images."}`;a.addAction("OK");await a.present()}
async function chooseBlock(lib){let blocks=lib.blocks||[];if(!blocks.length){let a=new Alert();a.title="No Image Blocks";a.message="Upload or publish an image block first.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Image Block";blocks.forEach(b=>a.addAction(`${b.title||"Untitled Block"}${b.visible===false?" [HIDDEN]":""}`));a.addCancelAction("Cancel");let i=await a.presentSheet();return i<0?null:{block:blocks[i],index:i}}
async function blockMenu(lib,i){let b=lib.blocks[i],a=new Alert();a.title=b.title;a.message=`${libCatLabel(b.category)}\n${(b.images||[]).length} image(s)\nID: ${b.id}`;a.addAction("Edit Title");a.addAction("Edit Summary");a.addAction("Edit Tags");a.addAction(b.visible===false?"Show Block":"Hide Block");a.addAction("Change Category");a.addAction("Add Images");a.addAction("Remove Images");a.addAction("Copy Block ID");a.addAction("Done");return await a.presentSheet()}
async function confirmRemove(title,msg){let a=new Alert();a.title=title;a.message=msg;a.addDestructiveAction("Remove");a.addCancelAction("Cancel");return await a.presentAlert()===0}
function shortPath(p){return String(p||"").split('/').pop()||p}
async function removeLibraryPhoto(lib,i){let imgs=lib.blocks[i].images||[];if(!imgs.length){let a=new Alert();a.title="No Images";a.message="This block has no images to remove.";a.addAction("OK");await a.present();return false}let a=new Alert();a.title="Remove Library Image";imgs.forEach((im,n)=>a.addAction(`${String(n+1).padStart(3,"0")} - ${shortPath(imgPath(im))}`));a.addCancelAction("Cancel");let x=await a.presentSheet();if(x<0)return false;let path=imgPath(imgs[x]);if(!await confirmRemove("Remove Image?",shortPath(path)))return false;if(path.startsWith("images/library/"))await del(path,`Remove library image: ${shortPath(path)}`);imgs.splice(x,1);lib.blocks[i].images=imgs;return true}
async function manageLibrary(libFile){let lib=normLib(libFile.json);LIBCATS=lib.categories;let sel=await chooseBlock(lib);if(!sel)return;let i=sel.index,changed=false;while(true){let c=await blockMenu(lib,i);if(c<0||c===8)break;if(c===0){let t=await ask("Edit Block Title","Title",lib.blocks[i].title);if(t){lib.blocks[i].title=t;changed=true}}else if(c===1){lib.blocks[i].summary=await ask("Edit Summary","Summary",lib.blocks[i].summary||"");changed=true}else if(c===2){lib.blocks[i].tags=splitTags(await ask("Edit Tags","Comma separated tags",(lib.blocks[i].tags||[]).join(", ")));changed=true}else if(c===3){lib.blocks[i].visible=lib.blocks[i].visible===false?true:false;changed=true}else if(c===4){lib.blocks[i].category=(await pickLibCat()).id;changed=true}else if(c===5){let items=await pickFileItems(),imgs=await uploadLibraryItems(items,lib.blocks[i],(lib.blocks[i].images||[]).length);lib.blocks[i].images.push(...imgs);changed=true}else if(c===6){changed=await removeLibraryPhoto(lib,i)}else if(c===7){Pasteboard.copyString(lib.blocks[i].id);let d=new Alert();d.title="Block ID Copied";d.message=lib.blocks[i].id;d.addAction("OK");await d.present()}if(changed){await saveLibraryLatest(lib,`Update image library block: ${lib.blocks[i].title}`);let d=new Alert();d.title="Saved";d.message="Choose another edit or tap Done.";d.addAction("OK");await d.present();changed=false}}}
function countsMsg(lib){let b=(lib.blocks||[]).filter(x=>x.visible!==false),photos=0,lines=[];for(let block of b){let n=(block.images||[]).filter(i=>typeof i==="string"||i.visible!==false).length;photos+=n;lines.push(`${block.title}: ${n} images`)}return[`Image Library: ${b.length} blocks / ${photos} images`,"",...lines].join("\n")}
async function menu(){let a=new Alert();a.title="Spray GenX Image Library";a.message=`Public image library manager\nDirect upload: JPG/PNG\nConverted publish: inbox JPEGs`;a.addAction("Upload JPG/PNG Block");a.addAction("Publish Converted Images");a.addAction("Manage Image Blocks");a.addAction("View Library Counts");a.addAction("View Converted Counts");a.addCancelAction("Cancel");return await a.presentAlert()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let libFile=await getJson(LIBRARY_PATH),lib=normLib(libFile.json);LIBCATS=lib.categories;let c=await menu();if(c===0)await uploadBlock(libFile);else if(c===1)await publishConvertedImages();else if(c===2)await manageLibrary(libFile);else if(c===3){let a=new Alert();a.title="Image Library Counts";a.message=countsMsg(lib);a.addAction("OK");await a.present()}else if(c===4)await convertedCounts()}catch(e){let a=new Alert();a.title="Error";a.message=String(e);a.addAction("OK");await a.present()}
