// Spray GenX Studio v1.5 - portfolio manager + image library uploader
// Replace only GITHUB_TOKEN. Master file lives in GitHub; paste into Scriptable.
const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",PORTFOLIO_PATH="data/portfolio.json",CATEGORIES_PATH="data/categories.json",SETTINGS_PATH="data/site-settings.json",LIBRARY_PATH="data/image-library.json",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE";
let CATS=[],LIBCATS=[];const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;
function slug(v){return String(v||"item").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"item"}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function today(){return new Date().toISOString().slice(0,10)}
function imgPath(i){return typeof i==="string"?i:(i&&i.path?i.path:"")}
function splitTags(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function normImgs(p){return(p.images||[]).map(i=>typeof i==="string"?{path:i,visible:true,caption:""}:{path:i.path||"",visible:i.visible===false?false:true,caption:i.caption||""}).filter(i=>i.path)}
function normPortfolio(p){p.projects=p.projects||[];p.projects=p.projects.map((x,n)=>{let imgs=normImgs(x),cover=x.cover||(imgs[0]?imgs[0].path:"");return{id:x.id||`${slug(x.title||"project")}-${n+1}`,category:x.category||catId(),title:x.title||"Untitled Project",description:x.description||"",visible:x.visible===false?false:true,cover,images:imgs}});return p}
function normCats(c){let arr=(c.categories||[]).map((x,n)=>({id:x.id||slug(x.label||`category-${n+1}`),label:x.label||x.id||`Category ${n+1}`,headline:x.headline||x.label||x.id||`Category ${n+1}`,visible:x.visible===false?false:true,sort:Number.isFinite(x.sort)?x.sort:(n+1)*10}));arr.sort((a,b)=>(a.sort||0)-(b.sort||0));return{categories:arr}}
function normLib(l){let cats=(l.categories||[]).map((x,n)=>({id:x.id||slug(x.label||`category-${n+1}`),label:x.label||x.id||`Category ${n+1}`,sort:Number.isFinite(x.sort)?x.sort:(n+1)*10})).sort((a,b)=>(a.sort||0)-(b.sort||0));let blocks=(l.blocks||[]).map((b,n)=>({id:b.id||`${slug(b.title||"image-block")}-${n+1}`,title:b.title||"Untitled Image Block",category:b.category||(cats[0]?cats[0].id:"uncategorized"),date:b.date||today(),summary:b.summary||b.description||"",tags:Array.isArray(b.tags)?b.tags:splitTags(b.tags),visible:b.visible===false?false:true,images:(b.images||[]).map(i=>typeof i==="string"?{path:i,caption:"",visible:true}:{path:i.path||"",caption:i.caption||"",visible:i.visible===false?false:true}).filter(i=>i.path)}));return{version:l.version||1,updated:today(),notes:l.notes||"Bulk image library for Spray GenX job photos.",categories:cats,blocks}}
function catId(){let c=CATS.find(x=>x.visible!==false)||CATS[0];return c?c.id:"commercial-interiors"}
function catLabel(id){let f=CATS.find(c=>c.id===id);return f?f.label:id}
function libCatLabel(id){let f=LIBCATS.find(c=>c.id===id);return f?f.label:id}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);if(!j.content||!j.sha)throw new Error(JSON.stringify(j,null,2));let txt=Data.fromBase64String(j.content.replace(/\n/g,"")).toRawString();return{json:JSON.parse(txt),sha:j.sha}}
async function getSha(path){try{let j=await gh(`${api(path)}?ref=${BRANCH}`);return j.sha||null}catch(e){return null}}
async function put(path,b64,msg,sha=null){let body={message:msg,content:b64,branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function del(path,msg){let sha=await getSha(path);if(!sha)return;return await gh(api(path),"DELETE",{message:msg,sha,branch:BRANCH})}
async function saveJson(path,obj,sha,msg){return await put(path,Data.fromString(JSON.stringify(obj,null,2)).toBase64String(),msg,sha)}
async function savePortfolioLatest(obj,msg){let latest=await getJson(PORTFOLIO_PATH);return await saveJson(PORTFOLIO_PATH,obj,latest.sha,msg)}
async function saveLibraryLatest(obj,msg){let latest=await getJson(LIBRARY_PATH);let data=normLib(obj);data.updated=today();return await saveJson(LIBRARY_PATH,data,latest.sha,msg)}
function stats(p){let s={};CATS.forEach(c=>s[c.id]={projects:0,photos:0});for(let pr of p.projects||[]){if(pr.visible===false||!s[pr.category])continue;s[pr.category].projects++;for(let im of pr.images||[])if(typeof im==="string"||im.visible!==false)s[pr.category].photos++}return s}
function statsMsg(p,lib=null){let s=stats(p),tp=0,tf=0,lines=[];for(let c of CATS.filter(x=>x.visible!==false)){tp+=s[c.id].projects;tf+=s[c.id].photos;lines.push(`${c.label}: ${s[c.id].projects} projects / ${s[c.id].photos} photos`)}if(lib){let b=(lib.blocks||[]).filter(x=>x.visible!==false),photos=0;b.forEach(x=>(x.images||[]).forEach(i=>{if(typeof i==="string"||i.visible!==false)photos++}));lines.unshift(`Image Library: ${b.length} blocks / ${photos} photos`,"") }return[`Portfolio: ${tp} projects / ${tf} photos`,"",...lines].join("\n")}
async function menu(){let a=new Alert();a.title="Spray GenX Studio";a.message="Portfolio + Image Library";a.addAction("New Portfolio Project");a.addAction("Manage Portfolio Projects");a.addAction("Upload Image Library Block");a.addAction("Manage Image Library");a.addAction("Manage Categories");a.addAction("View Counts");a.addAction("Replace Website Logo");a.addCancelAction("Cancel");return await a.presentAlert()}
async function pickCat(showHidden=false){let list=CATS.filter(c=>showHidden||c.visible!==false);let a=new Alert();a.title="Choose Category";list.forEach(c=>a.addAction(c.visible===false?`${c.label} [HIDDEN]`:c.label));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
async function pickLibCat(){let list=LIBCATS.length?LIBCATS:[{id:"uncategorized",label:"Uncategorized"}];let a=new Alert();a.title="Choose Image Library Category";list.forEach(c=>a.addAction(c.label));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return list[i]}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
async function askMulti(title,msg,fields){let a=new Alert();a.title=title;if(msg)a.message=msg;fields.forEach(f=>a.addTextField(f.placeholder||"",f.value||""));a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return fields.map((f,i)=>a.textFieldValue(i).trim())}
function jpegExt(path){return/\.(jpe?g)$/i.test(String(path||""))}
function logoExt(path){let p=String(path||"").toLowerCase();if(p.endsWith(".png"))return"png";if(p.endsWith(".jpg")||p.endsWith(".jpeg"))return"jpg";return""}
async function pickFileItems(){let out;try{out=await DocumentPicker.openFile(["public.jpeg","public.jpg"],true)}catch(e){out=await DocumentPicker.openFile()}let arr=Array.isArray(out)?out:[out],bad=arr.filter(p=>!jpegExt(p));if(bad.length)throw new Error("Only true .jpg/.jpeg files are allowed. Convert HEIC files to JPEG first.");let fm=FileManager.local();return arr.map(p=>({path:p,data:fm.read(p)}))}
async function uploadItems(items,category,title,start=0){let imgs=[],base=slug(title),time=stamp();for(let i=0;i<items.length;i++){let n=String(start+i+1).padStart(3,"0"),repoPath=`images/portfolio/${category}/${base}-${time}-${n}.jpg`;await put(repoPath,items[i].data.toBase64String(),`Upload portfolio image: ${title} ${n}`);imgs.push({path:repoPath,visible:true,caption:""})}return imgs}
async function uploadLibraryItems(items,block){let imgs=[],base=slug(block.title),time=stamp(),cat=block.category||"uncategorized";for(let i=0;i<items.length;i++){let n=String(i+1).padStart(3,"0"),repoPath=`images/library/${cat}/${base}-${time}-${n}.jpg`;await put(repoPath,items[i].data.toBase64String(),`Upload library image: ${block.title} ${n}`);imgs.push({path:repoPath,visible:true,caption:block.captionBase?`${block.captionBase} ${n}`:""})}return imgs}
async function replaceLogo(){let picked=await DocumentPicker.openFile(["public.png","public.jpeg","public.jpg"]),path=Array.isArray(picked)?picked[0]:picked,ext=logoExt(path);if(!ext)throw new Error("Choose a PNG or JPEG logo file.");let fm=FileManager.local(),repoPath=`images/logo-current.${ext}`;await put(repoPath,fm.read(path).toBase64String(),"Upload website logo",await getSha(repoPath));let settings;try{settings=await getJson(SETTINGS_PATH)}catch(e){settings={json:{},sha:null}}settings.json.logo=repoPath;await saveJson(SETTINGS_PATH,settings.json,settings.sha,"Update website logo setting");let a=new Alert();a.title="Logo Updated";a.message=`Website logo now points to:\n${repoPath}`;a.addAction("OK");await a.present()}
async function newProject(file){let p=normPortfolio(file.json),cat=await pickCat(),title=await ask("Project Name","Commercial Open Deck Ceiling");if(!title)throw new Error("Project name required");let desc=await ask("Description","Sprayed exposed ceiling structure for a clean, uniform commercial finish."),items=await pickFileItems();if(!items.length)throw new Error("No files selected");let imgs=await uploadItems(items,cat.id,title,0),id=`${slug(title)}-${stamp()}`;p.projects.push({id,category:cat.id,title,description:desc,visible:true,cover:imgs[0].path,images:imgs});await savePortfolioLatest(p,`Add portfolio project: ${title}`);let a=new Alert();a.title="Project Uploaded";a.message=`${title}\n\n${imgs.length} photo(s) uploaded to ${cat.label}.`;a.addAction("OK");await a.present()}
async function newLibraryBlock(libFile){let lib=normLib(libFile.json);LIBCATS=lib.categories;let cat=await pickLibCat(),vals=await askMulti("New Image Block","Quick fields now. AI naming/captioning can be added next.",[{placeholder:"Block title",value:"Commercial Black Ceiling"},{placeholder:"Summary",value:"Completed Spray GenX painting project."},{placeholder:"Tags comma separated",value:"painting, refinishing, completed work"},{placeholder:"Optional caption base",value:""}]),title=vals[0];if(!title)throw new Error("Block title required");let items=await pickFileItems();if(!items.length)throw new Error("No files selected");let block={id:`${slug(title)}-${stamp()}`,title,category:cat.id,date:today(),summary:vals[1],tags:splitTags(vals[2]),visible:true,captionBase:vals[3]};block.images=await uploadLibraryItems(items,block);delete block.captionBase;lib.blocks.push(block);await saveLibraryLatest(lib,`Add image library block: ${title}`);let a=new Alert();a.title="Image Block Uploaded";a.message=`${title}\n\n${block.images.length} photo(s) uploaded to ${cat.label}.\n\nBlock ID:\n${block.id}`;a.addAction("OK");await a.present()}
async function chooseProject(p){if(!p.projects.length){let a=new Alert();a.title="No Projects";a.message="There are no portfolio projects yet.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Project";p.projects.forEach(x=>a.addAction(`${x.title||"Untitled Project"}${x.visible===false?" [HIDDEN]":""}`));a.addCancelAction("Cancel");let i=await a.presentSheet();return i<0?null:{project:p.projects[i],index:i}}
async function chooseBlock(lib){let blocks=lib.blocks||[];if(!blocks.length){let a=new Alert();a.title="No Image Blocks";a.message="Upload an image library block first.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Image Block";blocks.forEach(b=>a.addAction(`${b.title||"Untitled Block"}${b.visible===false?" [HIDDEN]":""}`));a.addCancelAction("Cancel");let i=await a.presentSheet();return i<0?null:{block:blocks[i],index:i}}
async function projectMenu(p,i){let pr=p.projects[i],a=new Alert();a.title=pr.title;a.message=`${catLabel(pr.category)}\n${pr.images.length} photo(s)`;a.addAction("Edit Title");a.addAction("Edit Description");a.addAction(pr.visible===false?"Show Project":"Hide Project");a.addAction("Change Category");a.addAction("Add Photos");a.addAction("Remove Photos");a.addAction("Done");return await a.presentSheet()}
async function blockMenu(lib,i){let b=lib.blocks[i],a=new Alert();a.title=b.title;a.message=`${libCatLabel(b.category)}\n${(b.images||[]).length} photo(s)\nID: ${b.id}`;a.addAction("Edit Title");a.addAction("Edit Summary");a.addAction("Edit Tags");a.addAction(b.visible===false?"Show Block":"Hide Block");a.addAction("Change Category");a.addAction("Add Photos");a.addAction("Remove Photos");a.addAction("Copy Block ID");a.addAction("Done");return await a.presentSheet()}
async function confirm(title,msg){let a=new Alert();a.title=title;a.message=msg;a.addDestructiveAction("Remove");a.addCancelAction("Cancel");return await a.presentAlert()===0}
function shortPath(p){return String(p||"").split('/').pop()||p}
async function removePhoto(p,i){let imgs=p.projects[i].images||[];if(!imgs.length){let a=new Alert();a.title="No Photos";a.message="This project has no photos to remove.";a.addAction("OK");await a.present();return false}let a=new Alert();a.title="Remove Photo";a.message="Select one photo to remove.";imgs.forEach((im,n)=>a.addAction(`${String(n+1).padStart(3,"0")} - ${shortPath(imgPath(im))}`));a.addCancelAction("Cancel");let x=await a.presentSheet();if(x<0)return false;let path=imgPath(imgs[x]);if(!await confirm("Remove Photo?",shortPath(path)))return false;await del(path,`Remove portfolio image: ${shortPath(path)}`);imgs.splice(x,1);p.projects[i].images=imgs;p.projects[i].cover=imgs.length?imgPath(imgs[0]):"";return true}
async function removeLibraryPhoto(lib,i){let imgs=lib.blocks[i].images||[];if(!imgs.length){let a=new Alert();a.title="No Photos";a.message="This block has no photos to remove.";a.addAction("OK");await a.present();return false}let a=new Alert();a.title="Remove Library Photo";imgs.forEach((im,n)=>a.addAction(`${String(n+1).padStart(3,"0")} - ${shortPath(imgPath(im))}`));a.addCancelAction("Cancel");let x=await a.presentSheet();if(x<0)return false;let path=imgPath(imgs[x]);if(!await confirm("Remove Photo?",shortPath(path)))return false;await del(path,`Remove library image: ${shortPath(path)}`);imgs.splice(x,1);lib.blocks[i].images=imgs;return true}
async function manageProjects(file){let p=normPortfolio(file.json),sel=await chooseProject(p);if(!sel)return;let i=sel.index,changed=false;while(true){let c=await projectMenu(p,i);if(c<0||c===6)break;if(c===0){let t=await ask("Edit Title","Project title",p.projects[i].title);if(t){p.projects[i].title=t;changed=true}}else if(c===1){p.projects[i].description=await ask("Edit Description","Description",p.projects[i].description);changed=true}else if(c===2){p.projects[i].visible=p.projects[i].visible===false?true:false;changed=true}else if(c===3){p.projects[i].category=(await pickCat()).id;changed=true}else if(c===4){let items=await pickFileItems(),imgs=await uploadItems(items,p.projects[i].category,p.projects[i].title,p.projects[i].images.length);p.projects[i].images.push(...imgs);if(!p.projects[i].cover&&imgs[0])p.projects[i].cover=imgs[0].path;changed=true}else if(c===5){changed=await removePhoto(p,i)}if(changed){await savePortfolioLatest(p,`Update portfolio project: ${p.projects[i].title}`);let d=new Alert();d.title="Saved";d.message="Choose another edit or tap Done.";d.addAction("OK");await d.present();changed=false}}}
async function manageLibrary(libFile){let lib=normLib(libFile.json);LIBCATS=lib.categories;let sel=await chooseBlock(lib);if(!sel)return;let i=sel.index,changed=false;while(true){let c=await blockMenu(lib,i);if(c<0||c===8)break;if(c===0){let t=await ask("Edit Block Title","Title",lib.blocks[i].title);if(t){lib.blocks[i].title=t;changed=true}}else if(c===1){lib.blocks[i].summary=await ask("Edit Summary","Summary",lib.blocks[i].summary||"");changed=true}else if(c===2){lib.blocks[i].tags=splitTags(await ask("Edit Tags","Comma separated tags",(lib.blocks[i].tags||[]).join(", ")));changed=true}else if(c===3){lib.blocks[i].visible=lib.blocks[i].visible===false?true:false;changed=true}else if(c===4){lib.blocks[i].category=(await pickLibCat()).id;changed=true}else if(c===5){let items=await pickFileItems(),imgs=await uploadLibraryItems(items,lib.blocks[i]);lib.blocks[i].images.push(...imgs);changed=true}else if(c===6){changed=await removeLibraryPhoto(lib,i)}else if(c===7){Pasteboard.copyString(lib.blocks[i].id);let d=new Alert();d.title="Block ID Copied";d.message=lib.blocks[i].id;d.addAction("OK");await d.present()}if(changed){await saveLibraryLatest(lib,`Update image library block: ${lib.blocks[i].title}`);let d=new Alert();d.title="Saved";d.message="Choose another edit or tap Done.";d.addAction("OK");await d.present();changed=false}}}
async function manageCats(catFile){let data=normCats(catFile.json),a=new Alert();a.title="Manage Categories";a.message="Add, rename, hide/show, or edit headings. Hiding is safer than deleting.";a.addAction("Add Category");a.addAction("Edit Category");a.addAction("Hide/Show Category");a.addAction("Edit Headline");a.addCancelAction("Cancel");let c=await a.presentSheet();if(c<0)return;if(c===0){let label=await ask("New Category","Commercial Drywall");if(!label)return;let id=slug(label),sort=(data.categories.reduce((m,x)=>Math.max(m,x.sort||0),0)||0)+10;data.categories.push({id,label,headline:label,visible:true,sort})}else{let old=CATS;CATS=data.categories;let cat=await pickCat(true),idx=data.categories.findIndex(x=>x.id===cat.id);CATS=old;if(idx<0)return;if(c===1){let label=await ask("Rename Category","Category name",data.categories[idx].label);if(label)data.categories[idx].label=label}else if(c===2)data.categories[idx].visible=data.categories[idx].visible===false?true:false;else if(c===3)data.categories[idx].headline=await ask("Edit Headline","Section headline",data.categories[idx].headline||data.categories[idx].label)}await saveJson(CATEGORIES_PATH,data,catFile.sha,"Update portfolio categories");let d=new Alert();d.title="Categories Updated";d.message="Refresh website and Scriptable after category changes.";d.addAction("OK");await d.present()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let catFile=await getJson(CATEGORIES_PATH);CATS=normCats(catFile.json).categories;let file=await getJson(PORTFOLIO_PATH),p=normPortfolio(file.json),libFile=await getJson(LIBRARY_PATH),lib=normLib(libFile.json);LIBCATS=lib.categories;let c=await menu();if(c===0)await newProject(file);else if(c===1)await manageProjects(file);else if(c===2)await newLibraryBlock(libFile);else if(c===3)await manageLibrary(libFile);else if(c===4)await manageCats(catFile);else if(c===5){let a=new Alert();a.title="Spray GenX Counts";a.message=statsMsg(p,lib);a.addAction("OK");await a.present()}else if(c===6)await replaceLogo()}catch(e){let a=new Alert();a.title="Error";a.message=String(e);a.addAction("OK");await a.present()}
