// Spray GenX Studio v0.7 - compact Scriptable master
// Replace only GITHUB_TOKEN. Keep this master in GitHub; paste into Scriptable.
const OWNER="MobsterGit",REPO="-spraygenx-website-public",BRANCH="main",PORTFOLIO_PATH="data/portfolio.json",GITHUB_TOKEN="PASTE_NEW_TOKEN_HERE";
const CATS=[["commercial-ceilings","Commercial Ceilings"],["commercial-interiors","Commercial Interiors"],["block-metal","Block & Metal"],["machinery","Machinery & Cranes"],["epoxy","Epoxy Floors"],["residential","Residential"],["restoration","Restoration"]];
const api=p=>`https://api.github.com/repos/${OWNER}/${REPO}/contents/${p}`;
function slug(v){return String(v||"project").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"project"}
function stamp(){return new Date().toISOString().replace(/[-:T.Z]/g,"").slice(0,14)}
function catLabel(id){let f=CATS.find(c=>c[0]===id);return f?f[1]:id}
function normImgs(p){return(p.images||[]).map(i=>typeof i==="string"?{path:i,visible:true,caption:""}:{path:i.path||"",visible:i.visible===false?false:true,caption:i.caption||""}).filter(i=>i.path)}
function normPortfolio(p){p.projects=p.projects||[];p.projects=p.projects.map((x,n)=>{let imgs=normImgs(x),cover=x.cover||(imgs[0]?imgs[0].path:"");return{id:x.id||`${slug(x.title||"project")}-${n+1}`,category:x.category||"commercial-interiors",title:x.title||"Untitled Project",description:x.description||"",visible:x.visible===false?false:true,cover,images:imgs}});return p}
async function gh(url,method="GET",body=null){let r=new Request(url);r.method=method;r.headers={Authorization:`Bearer ${GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(body){r.headers["Content-Type"]="application/json";r.body=JSON.stringify(body)}let j=await r.loadJSON();if(j.message&&j.documentation_url)throw new Error(JSON.stringify(j,null,2));return j}
async function getJson(path){let j=await gh(`${api(path)}?ref=${BRANCH}`);if(!j.content||!j.sha)throw new Error(JSON.stringify(j,null,2));let txt=Data.fromBase64String(j.content.replace(/\n/g,"")).toRawString();return{json:JSON.parse(txt),sha:j.sha}}
async function put(path,b64,msg,sha=null){let body={message:msg,content:b64,branch:BRANCH};if(sha)body.sha=sha;return await gh(api(path),"PUT",body)}
async function savePortfolio(p,sha,msg){return await put(PORTFOLIO_PATH,Data.fromString(JSON.stringify(p,null,2)).toBase64String(),msg,sha)}
function stats(p){let s={};CATS.forEach(c=>s[c[0]]={projects:0,photos:0});for(let pr of p.projects||[]){if(pr.visible===false||!s[pr.category])continue;s[pr.category].projects++;for(let im of pr.images||[])if(typeof im==="string"||im.visible!==false)s[pr.category].photos++}return s}
function statsMsg(p){let s=stats(p),tp=0,tf=0,lines=[];for(let[c,l]of CATS){tp+=s[c].projects;tf+=s[c].photos;lines.push(`${l}: ${s[c].projects} projects / ${s[c].photos} photos`)}return[`Total: ${tp} projects / ${tf} photos`,"",...lines].join("\n")}
async function menu(p){let a=new Alert();a.title="Spray GenX Studio";a.message=statsMsg(p);a.addAction("New Project");a.addAction("Manage Projects");a.addAction("View Counts");a.addCancelAction("Cancel");return await a.presentAlert()}
async function pickCat(){let a=new Alert();a.title="Choose Category";CATS.forEach(c=>a.addAction(c[1]));a.addCancelAction("Cancel");let i=await a.presentSheet();if(i<0)throw new Error("Cancelled");return{id:CATS[i][0],label:CATS[i][1]}}
async function ask(title,ph,val=""){let a=new Alert();a.title=title;a.addTextField(ph,val);a.addAction("OK");a.addCancelAction("Cancel");let r=await a.presentAlert();if(r<0)throw new Error("Cancelled");return a.textFieldValue(0).trim()}
function jpegExt(path){return/\.(jpe?g)$/i.test(String(path||""))}
async function pickFiles(){let out;try{out=await DocumentPicker.openFile(["public.jpeg","public.jpg"],true)}catch(e){out=await DocumentPicker.openFile()}let arr=Array.isArray(out)?out:[out];let bad=arr.filter(p=>!jpegExt(p));if(bad.length)throw new Error("Only true .jpg/.jpeg files are allowed. Convert HEIC files to JPEG first.");return arr}
async function uploadFiles(paths,category,title,start=0){let fm=FileManager.local(),imgs=[],base=slug(title),time=stamp();for(let i=0;i<paths.length;i++){let n=String(start+i+1).padStart(3,"0"),repoPath=`images/portfolio/${category}/${base}-${time}-${n}.jpg`,data=fm.read(paths[i]);await put(repoPath,data.toBase64String(),`Upload portfolio image: ${title} ${n}`);imgs.push({path:repoPath,visible:true,caption:""})}return imgs}
async function newProject(file){let p=normPortfolio(file.json),cat=await pickCat(),title=await ask("Project Name","Commercial Open Deck Ceiling");if(!title)throw new Error("Project name required");let desc=await ask("Description","Sprayed exposed ceiling structure for a clean, uniform commercial finish."),files=await pickFiles();if(!files.length)throw new Error("No files selected");let imgs=await uploadFiles(files,cat.id,title,0),id=`${slug(title)}-${stamp()}`;p.projects.push({id,category:cat.id,title,description:desc,visible:true,cover:imgs[0].path,images:imgs});await savePortfolio(p,file.sha,`Add portfolio project: ${title}`);let a=new Alert();a.title="Project Uploaded";a.message=`${title}\n\n${imgs.length} photo(s) uploaded to ${cat.label}.`;a.addAction("OK");await a.present()}
function projectName(p){return`${p.title||"Untitled Project"}${p.visible===false?" [HIDDEN]":""}`}
async function chooseProject(p){if(!p.projects.length){let a=new Alert();a.title="No Projects";a.message="There are no portfolio projects yet.";a.addAction("OK");await a.present();return null}let a=new Alert();a.title="Choose Project";p.projects.forEach(x=>a.addAction(projectName(x)));a.addCancelAction("Cancel");let i=await a.presentSheet();return i<0?null:{project:p.projects[i],index:i}}
async function manage(file){let p=normPortfolio(file.json),sel=await chooseProject(p);if(!sel)return;let pr=sel.project,i=sel.index,a=new Alert();a.title=pr.title;a.message=`${catLabel(pr.category)}\n${pr.images.length} photo(s)`;a.addAction("Edit Title");a.addAction("Edit Description");a.addAction(pr.visible===false?"Show Project":"Hide Project");a.addAction("Change Category");a.addAction("Add Photos");a.addCancelAction("Cancel");let c=await a.presentSheet();if(c<0)return;if(c===0){let t=await ask("Edit Title","Project title",pr.title);if(t)p.projects[i].title=t}if(c===1)p.projects[i].description=await ask("Edit Description","Description",pr.description);if(c===2)p.projects[i].visible=pr.visible===false?true:false;if(c===3)p.projects[i].category=(await pickCat()).id;if(c===4){let files=await pickFiles(),imgs=await uploadFiles(files,p.projects[i].category,p.projects[i].title,p.projects[i].images.length);p.projects[i].images.push(...imgs);if(!p.projects[i].cover&&imgs[0])p.projects[i].cover=imgs[0].path}await savePortfolio(p,file.sha,`Update portfolio project: ${p.projects[i].title}`);let d=new Alert();d.title="Project Updated";d.message=p.projects[i].title;d.addAction("OK");await d.present()}
try{if(!GITHUB_TOKEN||GITHUB_TOKEN==="PASTE_NEW_TOKEN_HERE")throw new Error("Paste your GitHub token into GITHUB_TOKEN first.");let file=await getJson(PORTFOLIO_PATH),p=normPortfolio(file.json),c=await menu(p);if(c===0)await newProject(file);else if(c===1)await manage(file);else if(c===2){let a=new Alert();a.title="Portfolio Counts";a.message=statsMsg(p);a.addAction("OK");await a.present()}}catch(e){let a=new Alert();a.title="Error";a.message=String(e);a.addAction("OK");await a.present()}
